[package]
name = "open_meteo_wrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
open-meteo-api = "0.1.3"
reqwest = { version = "0.11", features = ["blocking"] }
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]
